openapi: 3.0.0
info:
  title: Friend+ API
  version: 1.0.0
  description: API for managing user friendships

paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request

  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the user
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

  /friend-requests:
    get:
      summary: Get a list of friend requests
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FriendRequest'
    post:
      summary: Send a friend request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FriendRequestInput'
      responses:
        '201':
          description: Friend request sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequest'
        '400':
          description: Bad request

  /friend-requests/{id}:
    get:
      summary: Get friend request by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the friend request
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequest'
        '404':
          description: Friend request not found

    delete:
      summary: Delete a friend request
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the friend request
      responses:
        '204':
          description: Friend request deleted successfully
        '404':
          description: Friend request not found

  /friends:
    get:
      summary: Get a list of friends
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'

  /friends/{id}:
    get:
      summary: Get friend by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
         